services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: meu-app-react:latest
    expose:
      - "${FRONTEND_PORT}:${FRONTEND_INTERNAL_PORT}"

    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge